Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 14:38:02.925984
Response status: 404 for GET /order in 0.01s
Request received: GET /order/ at 2025-04-07 14:38:02.943587
Response status: 200 for GET /order/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 14:56:52.108211
Response status: 404 for GET /order in 0.01s
Request received: GET /order/ at 2025-04-07 14:56:52.119203
Internal Server Error: /order/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 210, in _get_response
    response = middleware_method(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py", line 49, in process_template_response
    response.context_data['custom_message'] = "Added by middleware"
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
Response status: 500 for GET /order/ in 0.11s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 14:58:18.288194
Response status: 404 for GET /order in 0.01s
Request received: GET /order/ at 2025-04-07 14:58:18.309579
Internal Server Error: /order/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 213, in _get_response
    self.check_response(
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: SimpleLoggingMiddleware.process_template_response didn't return an HttpResponse object. It returned None instead.
Response status: 500 for GET /order/ in 0.11s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 14:58:43.963957
Response status: 404 for GET /order in 0.01s
Request received: GET /order/ at 2025-04-07 14:58:43.983777
Response status: 200 for GET /order/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 15:00:28.496869
Response status: 404 for GET /order in 0.01s
Request received: GET /order/ at 2025-04-07 15:00:28.611054
Response status: 200 for GET /order/ in 0.12s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 15:28:11.950525
Internal Server Error: /order
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py", line 63, in __call__
    if self.maintenance and not request.user.is_vendor:
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'is_vendor'
Response status: 500 for GET /order in 0.04s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 15:29:14.372820
Internal Server Error: /order
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py", line 63, in __call__
    if self.maintenance:
       ^^^^^^^^^^^^^^^^
AttributeError: 'MaintenanceModeMiddleware' object has no attribute 'maintenance'
Response status: 500 for GET /order in 0.03s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 15:29:32.110427
Response status: 404 for GET /order in 0.04s
Request received: GET /order/ at 2025-04-07 15:29:32.227911
Response status: 200 for GET /order/ in 0.11s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /order at 2025-04-07 15:29:42.968570
Response status: 503 for GET /order in 0.00s
Service Unavailable: /order
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\middleware.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\__init__.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/all at 2025-04-08 10:34:34.136837
Response status: 404 for GET /product/all in 0.01s
Request received: GET /product/all/ at 2025-04-08 10:34:34.156012
Response status: 401 for GET /product/all/ in 0.09s
Unauthorized: /product/all/
Request received: POST /user/login at 2025-04-08 10:34:41.174728
Response status: 200 for POST /user/login in 0.53s
Request received: GET /product/all at 2025-04-08 10:35:03.656213
Response status: 404 for GET /product/all in 0.00s
Request received: GET /product/all/ at 2025-04-08 10:35:03.666735
Internal Server Error: /product/all/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'all'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\generics.py", line 87, in get_object
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 83, in get_queryset
    return VendorProduct.objects.filter(product_id=product_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'all'.
Response status: 500 for GET /product/all/ in 0.24s
Request received: GET /vendor-product at 2025-04-08 10:35:16.974080
Response status: 404 for GET /vendor-product in 0.00s
Request received: GET /vendor-product/ at 2025-04-08 10:35:16.982384
Response status: 200 for GET /vendor-product/ in 0.07s
Request received: GET /vendor-product at 2025-04-08 10:35:24.770987
Response status: 404 for GET /vendor-product in 0.00s
Request received: GET /vendor-product/ at 2025-04-08 10:35:24.782537
Response status: 200 for GET /vendor-product/ in 0.07s
Request received: GET /vendor-product at 2025-04-08 10:35:26.104433
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:26.116715
Response status: 200 for GET /vendor-product/ in 0.08s
Request received: GET /vendor-product at 2025-04-08 10:35:27.238726
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:27.250695
Response status: 200 for GET /vendor-product/ in 0.06s
Request received: GET /vendor-product at 2025-04-08 10:35:28.271073
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:28.282663
Response status: 200 for GET /vendor-product/ in 0.16s
Request received: GET /vendor-product at 2025-04-08 10:35:29.420726
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:29.433750
Response status: 200 for GET /vendor-product/ in 0.07s
Request received: GET /vendor-product at 2025-04-08 10:35:30.587073
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:30.650006
Response status: 200 for GET /vendor-product/ in 0.08s
Request received: GET /vendor-product at 2025-04-08 10:35:31.951905
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:31.965961
Response status: 200 for GET /vendor-product/ in 0.15s
Request received: GET /vendor-product at 2025-04-08 10:35:33.270791
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:33.281498
Response status: 200 for GET /vendor-product/ in 0.06s
Request received: GET /vendor-product at 2025-04-08 10:35:34.316800
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:34.330809
Response status: 200 for GET /vendor-product/ in 0.06s
Request received: GET /vendor-product at 2025-04-08 10:35:35.432684
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:35.444584
Response status: 200 for GET /vendor-product/ in 0.06s
Request received: GET /vendor-product at 2025-04-08 10:35:36.496048
Response status: 404 for GET /vendor-product in 0.00s
Request received: GET /vendor-product/ at 2025-04-08 10:35:36.507523
Response status: 200 for GET /vendor-product/ in 0.06s
Request received: GET /vendor-product at 2025-04-08 10:35:37.533143
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:37.545955
Response status: 200 for GET /vendor-product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /vendor-product at 2025-04-08 10:35:57.075938
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:35:57.104377
Response status: 200 for GET /vendor-product/ in 0.09s
Request received: GET /vendor-product at 2025-04-08 10:36:42.742309
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:36:42.754811
Response status: 200 for GET /vendor-product/ in 0.17s
Request received: GET /product/all at 2025-04-08 10:37:29.219886
Response status: 404 for GET /product/all in 0.00s
Request received: GET /product/all/ at 2025-04-08 10:37:29.231305
Internal Server Error: /product/all/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'all'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\generics.py", line 87, in get_object
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 83, in get_queryset
    return VendorProduct.objects.filter(product_id=product_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'all'.
Response status: 500 for GET /product/all/ in 0.13s
Request received: GET /product at 2025-04-08 10:37:47.371209
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 10:37:47.386110
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 88, in list
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.18s
Request received: GET /vendor-product at 2025-04-08 10:38:19.399064
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 10:38:19.412208
Response status: 200 for GET /vendor-product/ in 0.06s
Request received: GET /product at 2025-04-08 10:38:33.985548
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 10:38:33.996103
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 88, in list
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.13s
Request received: GET /product/ at 2025-04-08 10:39:00.744185
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 88, in list
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.14s
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 10:40:40.123208
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 88, in list
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.12s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 11:32:21.102739
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 83, in get_queryset
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.15s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 11:35:55.438031
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 88, in list
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.13s
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 11:37:29.270730
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 88, in list
    cached_data = cache.get(cache_key)
                  ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__
  File "C:\Python311\Lib\site-packages\django_redis\client\default.py", line 258, in get
    value = client.get(key)
            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 1422, in get_connection
    connection.connect()
  File "C:\Python311\Lib\site-packages\redis\connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. No connection could be made because the target machine actively refused it.
Response status: 500 for GET /product/ in 2.14s
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 11:52:42.711527
Response status: 200 for GET /product/ in 0.15s
Request received: GET /product/ at 2025-04-08 11:52:49.233695
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product/ at 2025-04-08 11:52:51.615943
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product/ at 2025-04-08 11:52:52.967701
Response status: 200 for GET /product/ in 0.18s
Request received: GET /product/ at 2025-04-08 11:52:54.430118
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product/ at 2025-04-08 11:52:55.694765
Response status: 200 for GET /product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 11:54:33.936496
Response status: 200 for GET /product/ in 0.16s
Request received: GET /product/ at 2025-04-08 11:54:45.189371
Response status: 200 for GET /product/ in 0.07s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\order\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\order\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 12:36:47.737523
Response status: 200 for GET /product/ in 0.11s
Request received: GET /product/ at 2025-04-08 12:37:02.472783
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 12:38:12.122419
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product/ at 2025-04-08 12:38:18.922687
Response status: 200 for GET /product/ in 0.06s
Request received: GET /product/ at 2025-04-08 12:38:32.467924
Response status: 200 for GET /product/ in 0.05s
Request received: GET /product/ at 2025-04-08 12:38:40.161970
Response status: 200 for GET /product/ in 0.05s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 12:38:51.119999
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product/ at 2025-04-08 12:38:58.509400
Response status: 200 for GET /product/ in 0.05s
Request received: GET /product/ at 2025-04-08 12:39:03.521879
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product/ at 2025-04-08 12:44:34.361947
Response status: 200 for GET /product/ in 0.14s
Request received: GET /product/ at 2025-04-08 12:44:40.042047
Response status: 404 for GET /product/ in 0.05s
Not Found: /product/
Request received: GET /product/ at 2025-04-08 12:44:44.796840
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\pagination.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 13:01:23.331798
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:01:23.351891
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 13:01:32.587599
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:01:32.599234
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\pagination.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 13:01:55.107293
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:01:55.126527
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product at 2025-04-08 13:03:19.027155
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:03:19.040186
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 13:03:22.106505
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 13:03:22.120118
Response status: 200 for GET /product/ in 0.05s
Request received: GET /product at 2025-04-08 13:03:28.857768
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:03:28.868093
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 13:03:36.610622
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:03:36.624913
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 13:03:41.458467
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 13:03:41.470436
Response status: 200 for GET /product/ in 0.15s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 13:03:53.485159
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:03:53.502447
Response status: 200 for GET /product/ in 0.09s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\pagination.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 13:04:19.885686
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:04:19.897373
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 13:04:24.572813
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 13:04:24.583586
Response status: 200 for GET /product/ in 0.17s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 13:04:37.214297
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 13:04:37.233533
Response status: 200 for GET /product/ in 0.09s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\pagination.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:24:46.349774
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:24:46.364841
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 14:24:55.716861
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:24:55.738989
Response status: 200 for GET /product/ in 0.15s
Request received: GET /product at 2025-04-08 14:25:02.218809
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:25:02.231896
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\pagination.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\pagination.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:28:58.699021
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:28:58.712300
Response status: 200 for GET /product/ in 0.16s
Request received: GET /product at 2025-04-08 14:29:03.930964
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 14:29:03.940986
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:30:10.982035
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:30:10.999598
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 104, in list
    queryset = self.filter_queryset(self.get_queryset())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\generics.py", line 154, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\rest_framework\filters.py", line 327, in filter_queryset
    return queryset.order_by(*ordering)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\db\models\query.py", line 1701, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 2249, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Python311\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: discount_percent, id, price, product, product_id, vendor, vendor_id, vendorprod_cartitem, vendorprod_orderitem
Response status: 500 for GET /product/ in 0.21s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:30:46.081039
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:30:46.094125
Response status: 200 for GET /product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:34:06.586273
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:34:06.599871
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 14:35:20.373420
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 14:35:20.385949
Response status: 200 for GET /product/ in 0.21s
Request received: GET /product at 2025-04-08 14:35:25.474209
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:35:25.485744
Response status: 200 for GET /product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:35:45.647469
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:35:45.667498
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 14:36:25.858711
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:36:25.885231
Response status: 200 for GET /product/ in 0.09s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 14:38:58.729444
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:38:58.750647
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 14:39:04.805332
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 14:39:04.821230
Response status: 200 for GET /product/ in 0.19s
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:15:16.049773
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:15:16.071852
Response status: 200 for GET /product/ in 0.20s
Request received: GET /product at 2025-04-08 15:15:19.342431
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 15:15:19.373867
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 15:15:22.514299
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:15:22.536616
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 15:15:26.543361
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:15:26.565861
Response status: 200 for GET /product/ in 0.11s
Request received: GET /product at 2025-04-08 15:16:14.850004
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:16:14.870320
Response status: 200 for GET /product/ in 0.10s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:27:11.648306
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:27:11.660185
Response status: 200 for GET /product/ in 0.29s
Request received: GET /product at 2025-04-08 15:27:19.425862
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:27:19.449379
Response status: 200 for GET /product/ in 0.13s
Request received: GET /product at 2025-04-08 15:28:59.240601
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 15:28:59.268695
Response status: 200 for GET /product/ in 0.22s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:30:47.339257
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 15:30:47.365446
Response status: 200 for GET /product/ in 0.15s
Request received: GET /product at 2025-04-08 15:30:55.796474
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:30:55.818816
Response status: 200 for GET /product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:33:05.700581
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:33:05.734435
Fresh response served and cached.
Fresh response served and cached.
Response status: 200 for GET /product/ in 0.11s
Request received: GET /product at 2025-04-08 15:33:14.744723
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:33:14.773558
Fresh response served and cached.
Response status: 200 for GET /product/ in 0.11s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:37:57.897406
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:37:57.913288
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 15:38:02.255099
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:38:02.272062
Response status: 200 for GET /product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:38:18.604711
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 15:38:18.633500
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 15:38:31.171324
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:38:31.204359
Response status: 200 for GET /product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:40:46.130075
Response status: 404 for GET /product in 0.04s
Request received: GET /product/ at 2025-04-08 15:40:46.179324
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 84, in process_cache_response
    response = view_instance.finalize_response(request, response, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py", line 101, in finalize_response
    all_keys = cache._cache.keys('*') if hasattr(cache, '_cache') else 'Cannot inspect keys'
               ^^^^^^^^^^^^^^^^^^^^^^
TypeError: OrderedDict.keys() takes no arguments (1 given)
Response status: 500 for GET /product/ in 0.15s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:42:02.687924
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 15:42:02.707899
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 15:42:07.020674
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:42:07.061592
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:42:45.088649
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 15:42:45.115431
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 15:42:56.152924
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:42:56.183877
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:43:34.380988
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:43:34.413434
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 15:43:38.975053
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:43:39.078224
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:43:53.632236
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:43:53.652404
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 15:43:58.724564
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 15:43:58.733963
Response status: 200 for GET /product/ in 0.00s
Request received: GET /product at 2025-04-08 15:44:13.754382
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:44:13.769065
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 15:44:19.480739
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:44:19.495503
Response status: 200 for GET /product/ in 0.00s
Request received: GET /product at 2025-04-08 15:45:06.941193
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:45:06.960940
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:52:13.579956
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:52:13.601232
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product at 2025-04-08 15:52:19.003148
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:52:19.016645
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product at 2025-04-08 15:53:07.243095
Response status: 404 for POST /vendor-product in 0.01s
Internal Server Error: /vendor-product
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/vendor-product/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Request received: POST /vendor-product/ at 2025-04-08 15:53:19.820967
Response status: 201 for POST /vendor-product/ in 0.18s
Request received: GET /vendor-product at 2025-04-08 15:53:40.430623
Response status: 404 for GET /vendor-product in 0.01s
Request received: GET /vendor-product/ at 2025-04-08 15:53:40.484246
Response status: 200 for GET /vendor-product/ in 0.10s
Request received: GET /product at 2025-04-08 15:54:13.750916
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:54:13.759965
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product at 2025-04-08 15:54:30.708219
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 15:54:30.726550
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:56:54.372628
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:56:54.390163
Response status: 200 for GET /product/ in 0.08s
Request received: POST /vendor-product at 2025-04-08 15:57:23.998411
Response status: 404 for POST /vendor-product in 0.00s
Internal Server Error: /vendor-product
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/vendor-product/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
Request received: POST /vendor-product/ at 2025-04-08 15:57:33.442632
Response status: 201 for POST /vendor-product/ in 0.07s
Request received: GET /product at 2025-04-08 15:57:50.679051
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:57:50.693455
Response status: 200 for GET /product/ in 0.00s
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 15:59:21.815971
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:59:21.838445
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 15:59:26.018007
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 15:59:26.035444
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product/ at 2025-04-08 15:59:57.730526
Response status: 201 for POST /vendor-product/ in 0.08s
Request received: GET /product at 2025-04-08 16:02:01.256832
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:02:01.270408
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:05:02.296223
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:05:02.317544
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product at 2025-04-08 16:05:03.624147
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:05:03.635612
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product/ at 2025-04-08 16:05:32.258273
Response status: 201 for POST /vendor-product/ in 0.09s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:07:50.401474
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 16:07:50.422183
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 16:07:57.818836
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:07:57.845444
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:17:10.940938
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:17:10.961982
Response status: 200 for GET /product/ in 0.09s
Request received: POST /vendor-product/ at 2025-04-08 16:17:35.406888
Response status: 201 for POST /vendor-product/ in 0.07s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:18:05.953154
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:18:05.976239
Response status: 200 for GET /product/ in 0.07s
Request received: POST /vendor-product/ at 2025-04-08 16:19:05.549130
Response status: 201 for POST /vendor-product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:19:58.173968
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:19:58.197475
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 16:19:59.373462
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:19:59.386109
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product/ at 2025-04-08 16:20:03.790204
Response status: 201 for POST /vendor-product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:21:01.371193
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:21:01.393751
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 16:21:06.916483
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:21:06.927547
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product/ at 2025-04-08 16:21:14.635384
Response status: 201 for POST /vendor-product/ in 0.06s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\signals.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:37:35.704869
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 16:37:35.726947
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 120, in calculate_key
    return key_func(
           ^^^^^^^^^
TypeError: VendorProductViewSet.vendor_product_cache_key_func() got multiple values for argument 'view_instance'
Response status: 500 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 16:37:37.061486
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:37:37.072009
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 120, in calculate_key
    return key_func(
           ^^^^^^^^^
TypeError: VendorProductViewSet.vendor_product_cache_key_func() got multiple values for argument 'view_instance'
Response status: 500 for GET /product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:39:34.240396
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:39:34.266422
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 117, in calculate_key
    key_func = getattr(view_instance, self.key_func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VendorProductViewSet' object has no attribute 'vendor_product_cache_key_func'
Response status: 500 for GET /product/ in 0.13s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:40:14.315946
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:40:14.359594
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 117, in calculate_key
    key_func = getattr(view_instance, self.key_func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'VendorProductViewSet' object has no attribute 'product.views.vendor_product_cache_key_func'
Response status: 500 for GET /product/ in 0.12s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:40:58.133465
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:40:58.162582
Response status: 200 for GET /product/ in 0.18s
Request received: GET /product at 2025-04-08 16:41:11.337676
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:41:11.349266
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product/ at 2025-04-08 16:41:24.002563
Response status: 201 for POST /vendor-product/ in 0.08s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:49:26.663583
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 16:49:26.689934
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 120, in calculate_key
    return key_func(
           ^^^^^^^^^
TypeError: custom_cache_key_func() got multiple values for argument 'view_instance'
Response status: 500 for GET /product/ in 0.12s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\mixins.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:51:11.915091
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:51:11.933915
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 120, in calculate_key
    return key_func(
           ^^^^^^^^^
TypeError: CustomCacheResponseMixin.custom_cache_key_func() got multiple values for argument 'view_instance'
Response status: 500 for GET /product/ in 0.20s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\mixins.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:51:35.742635
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:51:35.772539
Internal Server Error: /product/
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 54, in inner
    return this.process_cache_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 70, in process_cache_response
    key = self.calculate_key(
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\rest_framework_extensions\cache\decorators.py", line 120, in calculate_key
    return key_func(
           ^^^^^^^^^
TypeError: 'str' object is not callable
Response status: 500 for GET /product/ in 0.11s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\mixins.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:53:22.884272
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:53:22.928200
Response status: 200 for GET /product/ in 0.11s
Request received: GET /product at 2025-04-08 16:53:26.134014
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 16:53:26.144122
Response status: 200 for GET /product/ in 0.00s
Request received: POST /vendor-product/ at 2025-04-08 16:53:39.597625
Response status: 201 for POST /vendor-product/ in 0.08s
Request received: GET /product at 2025-04-08 16:53:56.336958
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:53:56.360200
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:55:14.818378
Response status: 404 for GET /product in 0.02s
Request received: GET /product/ at 2025-04-08 16:55:14.844708
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 16:55:26.426651
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:55:26.440155
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:56:00.181144
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:56:00.208244
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product at 2025-04-08 16:56:05.611284
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 16:56:05.625274
Response status: 200 for GET /product/ in 0.00s
Request received: GET /product at 2025-04-08 16:56:58.550209
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:56:58.565846
Response status: 200 for GET /product/ in 0.00s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 16:59:32.955328
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 16:59:32.974449
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 16:59:47.387675
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 16:59:47.395721
Response status: 200 for GET /product/ in 0.08s
Request received: GET /product at 2025-04-08 17:00:00.736106
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:00:00.750291
Response status: 200 for GET /product/ in 0.06s
Request received: GET /product at 2025-04-08 17:00:16.834598
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 17:00:16.845033
Response status: 200 for GET /product/ in 0.14s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 17:02:12.906334
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:02:12.923489
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 17:02:22.818209
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:02:22.831472
Response status: 200 for GET /product/ in 0.09s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\product\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /product at 2025-04-08 17:12:16.561509
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:12:16.580072
Response status: 200 for GET /product/ in 0.10s
Request received: GET /product at 2025-04-08 17:12:39.599173
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:12:39.612698
Response status: 200 for GET /product/ in 0.07s
Request received: GET /product at 2025-04-08 17:12:45.273431
Response status: 404 for GET /product in 0.00s
Request received: GET /product/ at 2025-04-08 17:12:45.283813
Response status: 200 for GET /product/ in 0.06s
Request received: GET /product at 2025-04-08 17:12:51.647105
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:12:51.684331
Response status: 200 for GET /product/ in 0.03s
Request received: GET /product at 2025-04-08 17:16:22.176332
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:16:22.196141
Response status: 200 for GET /product/ in 0.09s
Request received: GET /product at 2025-04-08 17:22:15.772316
Response status: 404 for GET /product in 0.01s
Request received: GET /product/ at 2025-04-08 17:22:15.788051
Response status: 200 for GET /product/ in 0.09s
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\order\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /user/login at 2025-04-09 12:04:15.531842
Response status: 200 for POST /user/login in 1.80s
Request received: POST /order/ at 2025-04-09 12:04:43.020143
Response status: 201 for POST /order/ in 1.38s
Request received: POST /order/ at 2025-04-09 12:11:27.152227
Response status: 201 for POST /order/ in 0.15s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\tasks.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\order\views.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /order/ at 2025-04-09 12:16:58.646418
Response status: 201 for POST /order/ in 0.50s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\celery.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /order/ at 2025-04-09 12:22:47.021122
Response status: 201 for POST /order/ in 0.53s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\tasks.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /order/ at 2025-04-09 12:29:10.471604
Response status: 201 for POST /order/ in 0.24s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\tasks.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /order/ at 2025-04-09 12:30:34.029408
Response status: 201 for POST /order/ in 0.21s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /order/ at 2025-04-09 12:38:56.560739
Response status: 201 for POST /order/ in 0.23s
Request received: POST /order/ at 2025-04-09 12:50:30.941112
Response status: 201 for POST /order/ in 0.12s
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\celery.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\tasks.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\tasks.py changed, reloading.
Watching for file changes with StatReloader
Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x000001FBC480B810>> raised: ModuleNotFoundError("No module named 'django_celery_beat'")
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\fixups\django.py", line 82, in on_import_modules
    self.worker_fixup.validate_models()
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\fixups\django.py", line 120, in validate_models
    self.django_setup()
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\fixups\django.py", line 116, in django_setup
    django.setup()
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\apps\config.py", line 193, in create
    import_module(entry)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_celery_beat'
Signal handler <promise@0x1fbc4801450 --> <bound method Celery._autodiscover_tasks of <Celery core at 0x1fbc480af90>>> raised: AppRegistryNotReady("Apps aren't loaded yet.")
Traceback (most recent call last):
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\vine\promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\vine\promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\app\base.py", line 689, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\app\base.py", line 698, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
                                               ^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\app\base.py", line 701, in <listcomp>
    for pkg in fixup.autodiscover_tasks()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\celery\fixups\django.py", line 92, in autodiscover_tasks
    return [config.name for config in apps.get_app_configs()]
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\apps\registry.py", line 147, in get_app_configs
    self.check_apps_ready()
  File "C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\venv\Lib\site-packages\django\apps\registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Request received: GET /admin/ at 2025-04-09 16:29:34.048121
Response status: 404 for GET /admin/ in 0.02s
Not Found: /admin/
Request received: GET /favicon.ico at 2025-04-09 16:29:34.203311
Response status: 404 for GET /favicon.ico in 0.01s
Not Found: /favicon.ico
Request received: GET /admin/ at 2025-04-09 16:30:01.310870
Response status: 404 for GET /admin/ in 0.01s
Not Found: /admin/
Request received: GET /favicon.ico at 2025-04-09 16:30:01.422992
Response status: 404 for GET /favicon.ico in 0.01s
Not Found: /favicon.ico
Request received: GET /admin/ at 2025-04-09 16:30:09.418829
Response status: 404 for GET /admin/ in 0.01s
Not Found: /admin/
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\urls.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /admin/ at 2025-04-09 16:30:52.595116
Response status: 302 for GET /admin/ in 0.03s
Request received: GET /admin/login/ at 2025-04-09 16:30:52.628717
Response status: 200 for GET /admin/login/ in 0.09s
Request received: POST /admin/login/ at 2025-04-09 16:31:27.845184
Response status: 200 for POST /admin/login/ in 0.89s
Request received: POST /admin/login/ at 2025-04-09 16:32:00.427550
Response status: 200 for POST /admin/login/ in 0.77s
Request received: POST /admin/login/ at 2025-04-09 16:32:18.832116
Response status: 200 for POST /admin/login/ in 0.71s
Watching for file changes with StatReloader
Request received: POST /admin/login/ at 2025-04-09 16:33:57.505791
Response status: 302 for POST /admin/login/ in 0.80s
Request received: GET /admin/ at 2025-04-09 16:33:58.315271
Response status: 200 for GET /admin/ in 0.18s
Request received: GET /admin/django_celery_beat/periodictask/add/ at 2025-04-09 16:34:27.021443
Response status: 200 for GET /admin/django_celery_beat/periodictask/add/ in 0.32s
Request received: GET /admin/jsi18n/ at 2025-04-09 16:34:27.375990
Response status: 200 for GET /admin/jsi18n/ in 0.10s
Request received: GET /admin/django_celery_beat/crontabschedule/add/ at 2025-04-09 16:34:36.408386
Response status: 200 for GET /admin/django_celery_beat/crontabschedule/add/ in 0.24s
Request received: GET /admin/django_celery_beat/periodictask/add/ at 2025-04-09 16:35:28.459425
Response status: 200 for GET /admin/django_celery_beat/periodictask/add/ in 0.12s
Request received: GET /admin/django_celery_beat/clockedschedule/add/ at 2025-04-09 16:36:05.446843
Response status: 200 for GET /admin/django_celery_beat/clockedschedule/add/ in 0.07s
Request received: POST /admin/django_celery_beat/clockedschedule/add/ at 2025-04-09 16:36:16.207867
Response status: 200 for POST /admin/django_celery_beat/clockedschedule/add/ in 0.08s
Request received: GET /admin/django_celery_beat/clockedschedule/add/ at 2025-04-09 16:36:23.433246
Response status: 200 for GET /admin/django_celery_beat/clockedschedule/add/ in 0.08s
Request received: POST /admin/django_celery_beat/clockedschedule/add/ at 2025-04-09 16:37:09.994351
Response status: 200 for POST /admin/django_celery_beat/clockedschedule/add/ in 0.07s
Request received: POST /admin/django_celery_beat/periodictask/add/ at 2025-04-09 16:37:27.840791
Response status: 302 for POST /admin/django_celery_beat/periodictask/add/ in 0.08s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:37:27.926486
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.10s
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\tasks.py changed, reloading.
Watching for file changes with StatReloader
Request received: GET /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:38:32.717186
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/change/ in 0.23s
Request received: GET /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:38:36.103333
Response status: 200 for GET /admin/django_celery_beat/clockedschedule/2/change/ in 0.09s
Request received: POST /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:38:40.780517
Response status: 200 for POST /admin/django_celery_beat/clockedschedule/2/change/ in 0.08s
Request received: POST /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:38:47.436622
Response status: 302 for POST /admin/django_celery_beat/periodictask/2/change/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:38:47.532797
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.23s
Request received: GET /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:42:30.356170
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/change/ in 0.20s
Request received: GET /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:42:34.297231
Response status: 200 for GET /admin/django_celery_beat/clockedschedule/2/change/ in 0.11s
Request received: POST /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:42:43.370854
Response status: 200 for POST /admin/django_celery_beat/clockedschedule/2/change/ in 0.17s
Request received: POST /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:42:48.552761
Response status: 302 for POST /admin/django_celery_beat/periodictask/2/change/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:42:48.645899
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.08s
Request received: GET /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:47:29.149892
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/change/ in 0.11s
Request received: GET /admin/jsi18n/ at 2025-04-09 16:47:29.288407
Response status: 200 for GET /admin/jsi18n/ in 0.06s
Request received: GET /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:47:35.050673
Response status: 200 for GET /admin/django_celery_beat/clockedschedule/2/change/ in 0.18s
Request received: POST /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:47:41.703473
Response status: 200 for POST /admin/django_celery_beat/clockedschedule/2/change/ in 0.07s
Request received: POST /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:47:43.493449
Response status: 302 for POST /admin/django_celery_beat/periodictask/2/change/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:47:43.583552
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:49:02.484846
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/change/ in 0.16s
Request received: GET /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:49:05.795820
Response status: 200 for GET /admin/django_celery_beat/clockedschedule/2/change/ in 0.08s
Request received: POST /admin/django_celery_beat/clockedschedule/2/change/ at 2025-04-09 16:49:15.170519
Response status: 200 for POST /admin/django_celery_beat/clockedschedule/2/change/ in 0.08s
Request received: POST /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:49:17.523673
Response status: 302 for POST /admin/django_celery_beat/periodictask/2/change/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:49:17.613909
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:49:21.986651
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/change/ in 0.12s
Request received: POST /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:49:25.372441
Response status: 302 for POST /admin/django_celery_beat/periodictask/2/change/ in 0.19s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:49:25.567235
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.08s
Request received: POST /admin/django_celery_beat/periodictask/ at 2025-04-09 16:51:54.938696
Response status: 302 for POST /admin/django_celery_beat/periodictask/ in 0.06s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:51:55.006549
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.09s
Request received: GET /admin/django_celery_beat/periodictask/2/change/ at 2025-04-09 16:52:07.337552
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/change/ in 0.12s
Request received: GET /admin/django_celery_beat/periodictask/2/delete/ at 2025-04-09 16:52:14.982816
Response status: 200 for GET /admin/django_celery_beat/periodictask/2/delete/ in 0.09s
Request received: POST /admin/django_celery_beat/periodictask/2/delete/ at 2025-04-09 16:52:16.745616
Response status: 302 for POST /admin/django_celery_beat/periodictask/2/delete/ in 0.07s
Request received: GET /admin/django_celery_beat/periodictask/ at 2025-04-09 16:52:16.819426
Response status: 200 for GET /admin/django_celery_beat/periodictask/ in 0.08s
Request received: GET /admin/auth/group/ at 2025-04-09 16:52:29.818987
Response status: 200 for GET /admin/auth/group/ in 0.08s
Request received: GET /admin/authtoken/tokenproxy/ at 2025-04-09 16:52:31.733183
Response status: 200 for GET /admin/authtoken/tokenproxy/ in 0.07s
Request received: GET /admin/django_celery_beat/ at 2025-04-09 16:52:39.160440
Response status: 200 for GET /admin/django_celery_beat/ in 0.07s
Request received: GET /admin/ at 2025-04-09 16:52:41.647825
Response status: 200 for GET /admin/ in 0.07s
Request received: GET /admin/django_celery_beat/periodictask/add/ at 2025-04-09 16:52:49.308817
Response status: 200 for GET /admin/django_celery_beat/periodictask/add/ in 0.11s
Request received: GET / at 2025-04-09 16:53:00.881592
Response status: 401 for GET / in 0.03s
Unauthorized: /
Request received: GET /admin/django_celery_beat/periodictask/add/ at 2025-04-09 16:53:03.339622
Response status: 200 for GET /admin/django_celery_beat/periodictask/add/ in 0.11s
Request received: GET /admin/django_celery_beat/crontabschedule/add/ at 2025-04-09 16:55:52.775893
Response status: 200 for GET /admin/django_celery_beat/crontabschedule/add/ in 0.15s
Watching for file changes with StatReloader
C:\Users\Shankar.Samota\Desktop\Django_React\BlinkIt_App\backend\core\settings.py changed, reloading.
Watching for file changes with StatReloader
Request received: POST /user/login at 2025-05-21 15:12:00.781923
Response status: 200 for POST /user/login in 0.66s
